### ISSUE TITLE
Got the .db, how to generate the 3D map like yours?

### ISSUE THREAD

**Issue by pat-CIMAR-UF** [hemingchen/RoboND-Map-My-World-Robot#1]
Hi,
I am also one of the Udacity Robotics Software Engineer students. For this project, I already generated my .db data, but how could I generate the 3D map result like yours in RTAB-Map database viewer?
Many thanks.

**Comment by hemingchen** [comment]
If my memory serves me right, the 3D maps you mentioned were screenshots from the "real-time" map visualization tool `rtabmapviz` as SLAM goes on, whereas the 2D maps were screenshots of the offline visualization tool `rtabmap-databaseViewer` after the completion of SLAM.

During my time, Udacity's project document mentioned both tools in separate sections/pages. You can also check out official document of `rtabmapviz` here: [http://wiki.ros.org/rtabmap_ros#rtabmapviz](url)

**Comment by pat-CIMAR-UF** [comment]
Thanks.
